# -*- coding: utf-8 -*-
"""VISUAL QUESTION ANSWER MODEL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oeaLZi9F2bfBIXwwOUUrNYl1mdKr64Xp
"""

from PIL import Image
import requests
from transformers import AutoProcessor, BlipForQuestionAnswering

model = BlipForQuestionAnswering.from_pretrained("Salesforce/blip-vqa-base")
processor = AutoProcessor.from_pretrained("Salesforce/blip-vqa-base")

filename = input("Enter your filename : ")
image = Image.open("MahiRat.jpg")

text = "How many players are in the picture?"
label = "2"
inputs = processor(images=image, text=text, return_tensors="pt")
labels = processor(text=label, return_tensors="pt").input_ids

inputs["labels"] = labels
outputs = model(**inputs)
loss = outputs.loss
loss.backward()

text = input("Enter Your Question = ")
inputs = processor(images=image, text=text, return_tensors="pt")
outputs = model.generate(**inputs)
print(processor.decode(outputs[0], skip_special_tokens=True))

import requests
from PIL import Image
from transformers import BlipProcessor, BlipForQuestionAnswering

processor = BlipProcessor.from_pretrained("Salesforce/blip-vqa-base")
model = BlipForQuestionAnswering.from_pretrained("Salesforce/blip-vqa-base")


raw_image = Image.open("RoHiRat.png").convert('RGB')

question = "How many children are there?"
inputs = processor(raw_image, question, return_tensors="pt")

out = model.generate(**inputs)
print(processor.decode(out[0], skip_special_tokens=True))